apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:latest
        args:
          - --source=service
          - --source=ingress
          - --source=istio-gateway
          #- --istio-ingress-gateway=custom-istio-namespace/custom-istio-ingressgateway # load balancer service to be used; can be specified multiple times. Omit to use the default (istio-system/istio-ingressgateway)
          #- --domain-filter=xebik.art # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
          - --provider=google
          # `--google-project` is used to specify a project different from the
          # one external-dns is running inside
          - --google-project=xebikart-dev-1
          # Enable full synchronization. Set to `upsert-only` to prevent ExternalDNS from deleting any records
          - --policy=sync
          - --registry=txt
          - --txt-owner-id=xebikart-externaldns
