{{- if .Values.rabbitmq.rabbitmqCert.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
    name: custom-tls-certificate-secret
    labels:
        app: {{ template "rabbitmq-ha.name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        {{- if .Values.extraLabels }}
        {{ toYaml .Values.extraLabels | indent 4 }}
        {{- end }}
type: Opaque
data:
    cacert.pem: {{ .Files.Get .Values.global.certificates.cacertFilePath | b64enc | quote }}
    cert.pem: {{ .Files.Get .Values.global.certificates.certFilePath | b64enc | quote }}
    key.pem: {{ .Files.Get .Values.global.certificates.keyFilePath | b64enc | quote }}
{{- end }}

