apiVersion: v1
kind: Service
metadata:
  name: my-message-broker-service
  labels:
    app: message-broker
spec:
  type: LoadBalancer
  ports:
    - port: 5672
  selector:
    app: message-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-message-broker
  labels:
    app: message-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-broker
  template:
    metadata:
      labels:
        app: message-broker
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.7.13-alpine
          ports:
            - containerPort: 5672
          volumeMounts:
            - mountPath: /etc/rabbitmq/enabled_plugins
              name: rabbit-mq-config
      volumes:
        - name: rabbit-mq-config
          hostPath:
            path: ./config/enabled_plugins
            type: File