apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{.Values.metadata.name}}-deployment
    labels:
        app: {{.Values.labels.app}}
spec:
    replicas: {{.Values.replicaCount}}
    selector:
        matchLabels:
            app: {{.Values.labels.app}}
    template:
        metadata:
            labels:
                app: {{.Values.labels.app}}
        spec:
            containers:
                - name: {{.Values.image.name}}
                  image: {{.Values.image.name}}:{{.Values.image.tag}}
                  imagePullPolicy: {{.Values.image.imagePullPolicy}}
                  ports:
                      - containerPort: {{.Values.image.ports.containerPort}}
