apiVersion: v1
kind: Service
metadata:
    name: {{.Values.metadata.name}}-service
    labels:
        app: {{.Values.labels.app}}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        release: "{{.Release.Name}}"
        heritage: "{{.Release.Service}}"
spec:
    type: LoadBalancer
    ports:
        - port: {{.Values.image.ports.containerPort}}
    selector:
        app: {{.Values.labels.app}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{.Values.metadata.name}}-deployment
    labels:
        app: {{.Values.labels.app}}
spec:
    replicas: {{.Values.replicaCount}}
    selector:
        matchLabels:
            app: {{.Values.labels.app}}
    template:
        metadata:
            labels:
                app: {{.Values.labels.app}}
        spec:
            containers:
                - name: {{.Values.image.name}}
                  image: {{.Values.image.name}}:{{.Values.image.tag}}
                  ports:
                      - containerPort: {{.Values.image.ports.containerPort}}
