# Config for rabbitmq-ha (alias)
rabbitmq-ha:
  replicaCount: 2
  service:
    type: LoadBalancer
    # Explicitly override clusterIP so its default value doesn't conflict with LoadBalancer
    clusterIP: null
    annotations:
      external-dns.alpha.kubernetes.io/hostname: rabbitmq.xebik.art
  metadata:
    name: my-message-broker
  labels:
    app: message-broker
  rabbitmqMQTTPlugin:
    enabled: true
