rabbitmq-ha:
  replicaCount: 2
  extraLabels:
    type: infra
    layer: backend
  service:
    type: LoadBalancer
    # Explicitly override clusterIP so its default value doesn't conflict with LoadBalancer
    clusterIP: ""
    annotations:
      external-dns.alpha.kubernetes.io/hostname: rabbitmq.xebik.art
  rabbitmqMQTTPlugin:
    enabled: true
    # TODO: handler storage: https://www.rabbitmq.com/mqtt.html
    config: |
      mqtt.allow_anonymous = false
  extraPlugins: |
    rabbitmq_shovel,
    rabbitmq_shovel_management,
    rabbitmq_federation,
    rabbitmq_federation_management,
    rabbitmq_auth_mechanism_ssl,
    rabbitmq_trust_store,
  definitions:
    users: |-
      {"name": "xebikart1", "password": "xebikart1", "tags": "kart"},
      {"name": "xebikart2", "password": "xebikart2", "tags": "kart"},
      {"name": "xebikart3", "password": "xebikart3", "tags": "kart"},
      {"name": "backend", "password": "backend", "tags": "backend"}
    permissions: |-
      {"user": "xebikart1", "vhost": "/", "configure": "mqtt-subscription-*/*", "write": ".*", "read": ".*"},
      {"user": "xebikart2", "vhost": "/", "configure": "mqtt-subscription-*/*", "write": ".*", "read": ".*"},
      {"user": "xebikart3", "vhost": "/", "configure": "mqtt-subscription-*/*", "write": ".*", "read": ".*"},
      {"user": "backend", "vhost": "/", "configure": ".*", "write": ".*", "read": ".*"}
  prometheus:
    exporter:
      enabled: true
    operator:
      enabled: false
    alerts:
      enabled: false

