# This values file add TLS support for RabbbitMQ chart using custom certificates. Warning: This are self-signed
# certificates so they're are no recommended for prod-like environments
# FYI: this certificates have been created using tls-gen: https://github.com/michaelklishin/tls-gen

# RabbitMQ Chart configuration
rabbitmq:
  replicaCount: 2
  service:
    type: LoadBalancer
    # Explicitly override clusterIP so its default value doesn't conflict with LoadBalancer
    clusterIP: null
    annotations:
      external-dns.alpha.kubernetes.io/hostname: rabbitmq.xebik.art
  metadata:
    name: my-message-broker
  labels:
    app: message-broker
  rabbitmqMQTTPlugin:
    enabled: true
  rabbitmqUsername: "xebikart"
  rabbitmqPassword: "password"
  managementUsername: "management"
  managementPassword: "management"
  rabbitmqVhost: "/"
  rabbitmqMQTTPlugin:
    config: |-
      mqtt.allow_anonymous  = false
      mqtt.listeners.ssl.default = 8883
      mqtt.ssl_cert_login = true
# To use TLS CN as username
# mqtt.ssl_cert_login_from = common_name
  rabbitmqCert:
    enabled: true
    existingSecret: "custom-tls-certificate-secret"
  rabbitmqAmqpsSupport:
    enabled: true
    config: |
      ssl_options.verify = verify_peer
      ssl_options.fail_if_no_peer_cert = true
      ssl_options.cacertfile = /etc/cert/cacert.pem
      ssl_options.certfile = /etc/cert/cert.pem
      ssl_options.keyfile = /etc/cert/key.pem
      ssl_options.password = xebikart

  rabbitmqAuth:
    enabled: true
    config: |
      auth_mechanisms.1 = EXTERNAL # Needed ?
  # User authentication is done with TLS certificates
  definitions:
    users: |-
      {"name": "O=client,CN=fr.xebia.xebikart", "tags": "client"}
    permissions: |-
      {"user": "O=client,CN=fr.xebia.xebikart", "vhost": "/", "configure": ".*", "write": ".*", "read": ".*"}
    queues: |-
      {"name":"xebikart-events", "vhost":"/", "durable":true, "auto_delete":false, "arguments":{}}
    exchanges: |-
      {"name":"xebikart-exchange","vhost":"/","type":"direct","durable":true,"auto_delete":false,"internal":false,"arguments":{}}
    bindings: |-
      {"source":"xebikart-binding", "vhost":"/", "destination":"xebikart-events", "destination_type":"queue", "routing_key":"myKey", "arguments":{}}

