{
 "title": "Xebikart Dashboard",
 "description": "Rabbitmq stats and alerting using RabbitMQ Exporter (https://github.com/kbudde/rabbitmq_exporter)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "query": "label_values(rabbitmq_running, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Quick facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kart messages rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (user)(irate(rabbitmq_connection_received_packets{pod=\"xebikart-rabbitmq-ha-0\"}[1m]))",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Unacknowledged messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacknowledged{pod=\"$pod\"})",
     "legendFormat": "Unacknowledged messages"
    }
   ]
  },
  {
   "title": "Backend  messages rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rabbitmq_connection_received_packets{pod=\"$pod\", user=\"backend\"}[1m])",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(rabbitmq_node_mem_used{pod=\"$pod\"} / rabbitmq_node_mem_limit{pod=\"$pod\"})",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "Free disk space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(rabbitmq_node_disk_free{pod=\"$pod\"})",
     "legendFormat": "{{node}}:free"
    },
    {
     "expr": "max(rabbitmq_node_disk_free_limit{pod=\"$pod\"})",
     "legendFormat": "{{node}}:limit"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Used memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(rabbitmq_node_mem_used{pod=\"$pod\"})",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "max(rabbitmq_node_mem_limit{pod=\"$pod\"})",
     "legendFormat": "{{node}}:limit"
    }
   ]
  }
 ]
}