{
 "title": "Xebikart API Rest",
 "time": { "from": "2019-11-24T10:43:03.046Z", "to": "2019-11-24T10:54:07.844Z" },
 "templating": {
  "list": [
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(jvm_memory_bytes_init{service=\"xebikart-state-api\"}, pod)"
   },
   {
    "name": "Quantile",
    "label": "Quantile",
    "query": "label_values(xebikart_state_api_http_request_duration_seconds{service=\"xebikart-state-api\"}, quantile)"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{pod=\"$Pod\"}*1000"
    }
   ]
  },
  {
   "title": "HTTP calls",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(jetty_requests_total{pod=\"$Pod\"}[1m])"
    }
   ]
  },
  {
   "title": "MQTT received messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "pps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(xebikart_state_api_mqtt_received_messages_total{pod=\"$Pod\"}[1m])"
    }
   ]
  },
  {
   "title": "MQTT published messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "pps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(xebikart_state_api_mqtt_published_messages_total{pod=\"$Pod\"}[1m])"
    }
   ]
  },
  { "title": "Rest Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Endpoint Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(xebikart_state_api_http_requests_total{pod=\"$Pod\"}[1m])",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Endpoint latency by quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "xebikart_state_api_http_request_duration_seconds{pod=\"$Pod\", quantile=\"$Quantile\"} * 1000",
     "legendFormat": "{{method}} {{exported_endpoint}} "
    }
   ]
  },
  {
   "title": "HTTP responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(xebikart_state_api_http_requests_total{pod=\"$Pod\", exported_endpoint=~\"/api/mode/*\", method=\"POST\", status=~\"2..\"}[1m])",
     "legendFormat": "2XX => POST /api/mode "
    },
    {
     "expr": "irate(xebikart_state_api_http_requests_total{pod=\"$Pod\", exported_endpoint=~\"/api/mode/*\", status=~\"4..\"}[1m])",
     "legendFormat": "4XX => {{method}} /api/mode "
    },
    {
     "expr": "irate(xebikart_state_api_http_requests_total{pod=\"$Pod\", exported_endpoint=~\"/api/universe/*\", status=~\"2..\"}[1m])",
     "legendFormat": "2XX => {{method}} /api/mode "
    },
    {
     "expr": "irate(xebikart_state_api_http_requests_total{pod=\"$Pod\", exported_endpoint=~\"/api/universe/*\", status=~\"4..\"}[1m])",
     "legendFormat": "4XX => {{method}} /api/mode "
    },
    {
     "expr": "irate(xebikart_state_api_http_requests_total{pod=\"$Pod\", exported_endpoint=~\"/api/universe/*\", status=~\"5..\"}[1m])",
     "legendFormat": "5XX => {{method}} /api/mode "
    },
    {
     "expr": "sum(irate(xebikart_state_api_http_requests_total{pod=\"$Pod\", status=~\"2..\"}[1m]))",
     "legendFormat": "2XX => Global"
    },
    {
     "expr": "sum(irate(xebikart_state_api_http_requests_total{pod=\"$Pod\", status=~\"5..\"}[1m]))",
     "legendFormat": "5XX => Global"
    },
    {
     "expr": "sum(irate(xebikart_state_api_http_requests_total{pod=\"$Pod\", status=~\"4..\"}[1m]))",
     "legendFormat": "4XX => Global"
    }
   ]
  },
  { "title": "MQTT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "MQTT topic rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(xebikart_state_api_mqtt_received_messages_total{pod=\"$Pod\"}[1m])",
     "legendFormat": "Received in {{topic}}"
    },
    {
     "expr": "irate(xebikart_state_api_mqtt_published_messages_total{pod=\"$Pod\"}[1m])",
     "legendFormat": "Published in {{topic}}"
    }
   ]
  },
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jetty_requests_total{pod=\"$Pod\"}[1m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{pod=\"$Pod\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{pod=\"$Pod\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{pod=\"$Pod\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{pod=\"$Pod\", area=\"nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{pod=\"$Pod\", area=\"nonheap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{pod=\"$Pod\", area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{pod=\"$Pod\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{pod=\"$Pod\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{pod=\"$Pod\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{pod=\"$Pod\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon{pod=\"$Pod\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak{pod=\"$Pod\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{pod=\"$Pod\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{pod=\"$Pod\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{pod=\"$Pod\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_max_fds{pod=\"$Pod\"}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}